#!/bin/sh
//Thanks to the previous question and the reverse DNS find the name of your host
//Это DNS-сервер.
// объяснение
// На пятый вопрос мы выяснили, что IP-адрес 192.168.22.31 указывает на DNS-сервер. командой ifconfig en0 | grep 'inet ' | cut -d ' ' -f2

host 192.168.22.31